using Den.Tools;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpearCheckHit : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void OnTriggerEnter(Collider other)
    {
        // 衝突したオブジェクトの名前を取得
        string otherObjectName = other.gameObject.name;

        // コンソールにメッセージを表示
        Debug.Log($"やりと{otherObjectName}が衝突しました！");

        // ここで何か別のアクションを実行できます
        // 例: スコアを加算する、オブジェクトを破壊するなど
    }

    private void OnCollisionEnter(Collision collision)
    {
        // 衝突したオブジェクトの名前を取得
        string otherObjectName = collision.gameObject.name;

        // コンソールにメッセージを表示
        Debug.Log($"やりと{otherObjectName}が衝突しました！");

        // ここで何か別のアクションを実行できます
        // 例: スコアを加算する、オブジェクトを破壊するなど
    }
}

